apiVersion: v1
kind: Pod

metadata:
  name: pg-pod
  labels:
    name: pg-pod
    app: demo-app
spec:
  containers:
    - name: pg
      image: postgres:9.4
      ports:
        - containerPort: 5432
        
      