apiVersion: v1
kind: Pod

metadata:
  name: voting-app-worker
  labels:
    name: voting-app-worker
    app: demo
spec:
  containers:
    - name: voting-app-worker
      image: dockersamples/examplevotingapp_worker
      
      