apiVersion: v1
kind: Pod

metadata:
  name: voting-app-result
  labels:
    name: voting-app-result
    app: demo
spec:
  containers:
    - name: voting-app-result
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80
        
      